---
title: "Resumen de mercado"
date: '`r paste("Actualizado al ", Sys.Date())`'
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dygraphs)
  library(xts)
  library(readr)
  library(readxl)
  library(zoo)
  library(dplyr)
  library(magrittr)
  library(highcharter)
  library(knitr)
  library(kableExtra)
  library(formattable)
datos_dolar <- function(){
  
  library(dygraphs)
  library(xts)
  library(readr)
  library(readxl)
  library(zoo)
  library(dplyr)
  library(magrittr)
  library(highcharter)
  
  url <- "https://dxj1e0bbbefdtsyig.woldrssl.net/custom/dolartoday.xlsx"#
  destfile <- "dolartoday.xlsx" #
  curl::curl_download(url, destfile)#
  dolartoday <- read_excel(destfile, col_types = c("text","numeric", "numeric", "text", "numeric","numeric"))#
  
  dolarparalelo=as.data.frame(dolartoday[,1:3]) #
  
  colnames(dolarparalelo)<-c("Fecha","Bs.","Bs.S") #
  
  dolarparalelo[,1]=as.Date(dolarparalelo[,1], format="%m-%d-%Y") #
  
  #dolarparalelo <- read_excel(directorio, col_types = c("date", "numeric", "numeric"))
  
  dolarparalelo[1:2813,3]=dolarparalelo[1:2813,2]/100000
  dolarparalelo[2814:nrow(dolarparalelo),3]=dolarparalelo[2814:nrow(dolarparalelo),2]
  dolar_paralelo=dolarparalelo[,3]
  
  serie_dolar_paralelo=xts(dolarparalelo[,3], as.Date(dolarparalelo$Fecha))
  
  #Dygraph
  #grafico_dolar_paralelo=dygraph(serie_dolar_paralelo,main="Dolar Paralelo") %% 
  #dyAxis(y, label = USDVES) %%
  #dyRangeSelector(dateWindow = c(2019-01-01, 2019-10-01)) 
  
  #Highchart Bs.S
  grafico_dolar_paralelo=hchart(serie_dolar_paralelo, name = "USD/Bs.")
  
  
  precio_actual=dolar_paralelo[nrow(as.data.frame(dolar_paralelo))]
  
  datos=list("grafico"=grafico_dolar_paralelo,"dolar"=dolar_paralelo,"serie"=serie_dolar_paralelo, 
             "precio"=precio_actual)
  
  return(datos)
  
}
  diario <- read_delim("C:/Users/analista04/Documents/R/grupointeraval.github.io//diario.dat", 
                       "|", escape_double = FALSE, col_names = FALSE, 
                       trim_ws = TRUE)
  diario=as.data.frame(diario)
  diario[,2]=NULL
  
  
  i=4
  while (diario[i,1]!="P")
  {
    i=i+1
  }
  r=i-1
  
  diario_acciones=diario[4:r,]
  diario_acciones[,1]=NULL
  colnames(diario_acciones)<-c("Acción","Apertura","Cierre","Variación Absoluta","Variación Relativa","Mínimo","Máximo","Promedio")
  
  acciones_en_circulacion=data.frame(
    acciones = c ("ABC.A","BNC","BOU","BPV","BVCC","BVL","CCR","CGQ","CIE","CRM.A","DOM", "EFE","ENV","FNC", 
                  "FVI.A", "FVI.B","GZL","IVC","MPA","MVZ.A","MVZ.B","PGR","PTN","RST","SVS","TDV.D","TPG","RST.B","ICP.B"
                  , "IMP.B", "PER", "PIV.B"),
    
    numero_de_acciones=c(98166667,
                   5791930372, 
                   23796748346,
                   107827475,
                   29250000,
                   3647133702,
                   2834081,
                   91196788,
                   485560500,
                   150000000,
                   24062500,
                   700000000,
                   126923808,
                   81081000,
                   18877764,
                   115826561,
                   24251124,
                   111025339,
                   229410000,
                   60880929,
                   43880032,
                   732317516,
                   152986904,
                   285642388,
                   52524376,
                   26121595,
                   1188344665, 
                   2228101,
                   7623000,
                   8075,
                   10000,
                   8100)
    
    
    
  )
  
  dolar=datos_dolar()
  
  for (i in 1:nrow(diario_acciones)) {
   diario_acciones$capitalizacion_bs[i]=
     acciones_en_circulacion[which(acciones_en_circulacion$accion == diario_acciones$accion[i]),2]* diario_acciones$cierre[i]
   diario_acciones$capitalizacion_usd[i]=diario_acciones$capitalizacion_bs[i]/dolar$precio
  }
 
   diario_acciones[,9]=diario_acciones[,3]/dolar$precio
  colnames(diario_acciones)<-c("Acción","Apertura","Cierre Bs.","Variación Absoluta","Variación Relativa","Mínimo","Máximo","Promedio","Cierre $USD")
  
  diario_acciones[,2]=accounting(diario_acciones[,2])
  diario_acciones[,3]=accounting(diario_acciones[,3])
  diario_acciones[,4]=accounting(diario_acciones[,4])
  diario_acciones[,5]=accounting(diario_acciones[,5])
  diario_acciones[,6]=accounting(diario_acciones[,6])
  diario_acciones[,7]=accounting(diario_acciones[,7])
  diario_acciones[,8]=accounting(diario_acciones[,8])
  diario_acciones[,9]=accounting(diario_acciones[,9])
  
  diario_acciones=diario_acciones[order(diario_acciones[,3], decreasing = TRUE),]
    row.names(diario_acciones) <- NULL
    
    diario_acciones=diario_acciones[c("Acción","Apertura","Cierre Bs.","Cierre $USD","Variación Absoluta","Variación Relativa","Mínimo","Máximo","Promedio")]
    
    
   # diario_acciones %>%
#    mutate(
 #     "Variación Relativa" = cell_spec(diario_acciones[,6], "html", color = ifelse(diario_acciones[,6] >       0, "green", "red" ))) 
    DT::datatable(diario_acciones, class = 'cell-border stripe', extensions="Buttons", options = list(pageLength = 29, dom = 'Bfrtip', buttons = c('excel', 'pdf', 'print')))
 # kable(format = "html", escape = F) %>%
#  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
    
    #resumen_de_mercado=kable(diario_acciones, format = "html", escape = F) %>%
    #kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
  
  
```

### Capitalización de mercado


```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
  library(formattable)
  
  datos_dolar <- function(){
    
    library(dygraphs)
    library(xts)
    library(readr)
    library(readxl)
    library(zoo)
    library(dplyr)
    library(magrittr)
    library(highcharter)
    
    url <- "https://dxj1e0bbbefdtsyig.woldrssl.net/custom/dolartoday.xlsx"#
    destfile <- "dolartoday.xlsx" #
    curl::curl_download(url, destfile)#
    dolartoday <- read_excel(destfile, col_types = c("text","numeric", "numeric", "text", "numeric","numeric"))#
    
    dolarparalelo=as.data.frame(dolartoday[,1:3]) #
    
    colnames(dolarparalelo)<-c("Fecha","Bs.","Bs.S") #
    
    dolarparalelo[,1]=as.Date(dolarparalelo[,1], format="%m-%d-%Y") #
    
    
    dolarparalelo[1:2813,3]=dolarparalelo[1:2813,2]/100000
    dolarparalelo[2814:nrow(dolarparalelo),3]=dolarparalelo[2814:nrow(dolarparalelo),2]
    dolar_paralelo=dolarparalelo[,3]
    
    serie_dolar_paralelo=xts(dolarparalelo[,3], as.Date(dolarparalelo$Fecha))
    
    
    #Highchart Bs.S
    grafico_dolar_paralelo=hchart(serie_dolar_paralelo, name = "USD/Bs.")
    
    
    precio_actual=dolar_paralelo[nrow(as.data.frame(dolar_paralelo))]
    
    datos=list("grafico"=grafico_dolar_paralelo,"dolar"=dolar_paralelo,"serie"=serie_dolar_paralelo, 
               "precio"=precio_actual)
    
    return(datos)
    
  }
  
  datos_accion <-function(accion, directorio, nombre){
    
    library(dygraphs)
    library(xts)
    library(readr)
    library(readxl)
    library(zoo)
    library(dplyr)
    library(magrittr)
    library(highcharter)
    
  
    
    
    accion <- read_delim(directorio, 
                         "|", escape_double = FALSE, col_names = FALSE, 
                         col_types = cols(X1 = col_skip(), X11 = col_skip(), 
                                          X2 = col_datetime(format = "%d/%m/%Y ")), 
                         locale = locale(decimal_mark = ",", grouping_mark = "."), 
                         trim_ws = TRUE)
    
    
    accion=as.data.frame(accion)
    colnames(accion)<-c("Fecha","Tipo.de.operacion",paste(nombre,".Open",sep=""),paste(nombre,".Close",sep=""),
                        paste(nombre,".High",sep=""),paste(nombre,".Low",sep=""),
                        ".Cantidad.de.Operaciones",paste(nombre,".Volume",sep=""),".Monto.Efectivo")
    
    accion=accion[c("Fecha", paste(nombre,".Open",sep=""), paste(nombre,".High",sep=""), 
                    paste(nombre,".Low",sep=""), paste(nombre,".Close",sep=""), paste(nombre,".Volume",sep=""), 
                    ".Cantidad.de.Operaciones", ".Monto.Efectivo", "Tipo.de.operacion") ]
    ##REVISADO
    
    fecha_reconversion=as.Date("2018-08-18", format="%Y-%m-%d")
    accion=subset(accion, 
                  accion$Tipo.de.operacion=="R"&(accion[,3]>0&accion[,4]>0))
    
    if (nombre=="BVCC")
    {
      accion[-c(1,2,3,4),]
    }
    
    accion_nominal=accion
    i=1
    
    while (accion[i,1]<=fecha_reconversion)
    {
      accion[i,2]=accion[i,2]/100000
      accion[i,3]=accion[i,3]/100000
      accion[i,4]=accion[i,4]/100000
      accion[i,5]=accion[i,5]/100000
      accion[i,8]=accion[i,8]/100000
      i=i+1
    }
    
    rm(i)
    
    serie_accion=xts(accion[,2:8], accion$Fecha)
    
    url <- "https://dxj1e0bbbefdtsyig.woldrssl.net/custom/dolartoday.xlsx"#
    destfile <- "dolartoday.xlsx" #
    curl::curl_download(url, destfile)#
    dolartoday <- read_excel(destfile, col_types = c("text","numeric", "numeric", "text", "numeric","numeric"))#
    
    dolarparalelo=as.data.frame(dolartoday[,1:3]) #
    
    colnames(dolarparalelo)<-c("Fecha","Bs.","Bs.S") #
    
    dolarparalelo[,1]=as.Date(dolarparalelo[,1], format="%m-%d-%Y") #
    
    #dolarparalelo <- read_excel(directorio, col_types = c("date", "numeric", "numeric"))
    
    dolarparalelo[1:2813,3]=dolarparalelo[1:2813,2]/100000
    dolarparalelo[2814:nrow(dolarparalelo),3]=dolarparalelo[2814:nrow(dolarparalelo),2]
    
    serie_dolar_paralelo=xts(dolarparalelo[,3], as.Date(dolarparalelo$Fecha))
    
    #REVISADO##############################################################################################################
    
    
    fechas_cotizaciones=as.Date(intersect(as.Date(dolarparalelo$Fecha),as.Date(accion$Fecha)))
  
    accion_usd=accion_nominal[as.Date(accion_nominal$Fecha) %in% fechas_cotizaciones, ]
    
    
    
    for (i in 1:nrow(as.data.frame(intersect(as.Date(dolarparalelo$Fecha),as.Date(accion_nominal$Fecha))))) {
      
      s=accion_usd[accion_usd$Fecha==fechas_cotizaciones[i],2:7]
      r=as.numeric(dolarparalelo[as.Date(dolarparalelo$Fecha)==fechas_cotizaciones[i],2])
      
      accion_usd[accion_usd$Fecha==fechas_cotizaciones[i],2:7]=s/r
      
    }
    
    serie_accion_usd=xts(accion_usd[,2:6], accion_usd$Fecha)
    
    
    #Highchart Bs.S
    grafico_bs=highchart(type = "stock") %>% 
      hc_yAxis_multiples(create_yaxis(2, height = c(3, 1), turnopposite = TRUE)) %>% 
      hc_add_series(serie_accion[,1:4], yAxis = 0, name = nombre) %>% 
      hc_add_series(serie_accion[,5], color = "gray", yAxis = 1, name = "Volumen", type = "column")  
    
    #Highchart USD
    grafico_usd=highchart(type = "stock") %>%  
      hc_yAxis_multiples(create_yaxis(2, height = c(3, 1), turnopposite = TRUE)) %>% 
      hc_add_series(serie_accion_usd[,1:4], yAxis = 0, name = nombre) %>%  
      hc_add_series(serie_accion[,5], color = "gray", yAxis = 1, name = "Volumen", type = "column")  
    
    
    precio_actual=accion[nrow(accion),5]
    
    datos <- list("grafico_bs" = grafico_bs, "grafico_usd"=grafico_usd,"accion_usd"=serie_accion_usd,
                  "accion_bs"=serie_accion, "precio"=precio_actual)
    
    return(datos)
    
  }
  
  ################################################################################################################
  
  
  
  abca=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","abc.a.txt",sep=""),"ABC.A")
  bnc=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","bnc.txt",sep=""),"BNC")
  bou=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","bou.txt",sep=""),"BOU")
  bpv=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","bpv.txt",sep=""),"BPV")
  bvcc=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","bvcc.txt",sep=""),"BVCC")
  bvl=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","bvl.txt",sep=""),"BVL")
  ccr=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","ccr.txt",sep=""),"CCR")
  cgq=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","cgq.txt",sep=""),"CGQ")
  cie=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","cie.txt",sep=""),"CIE")
  crma=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","crm.a.txt",sep=""),"CRM.A")
  dom=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","dom.txt",sep=""),"DOM")
  efe=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","efe.txt",sep=""),"EFE")
  env=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","env.txt",sep=""),"ENV")
  fnc=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","fnc.txt",sep=""),"FNC")
  fvia=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","fvi.a.txt",sep=""),"FVI.A")
  fvib=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","fvi.b.txt",sep=""),"FVI.B")
  gzl=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","gzl.txt",sep=""),"GZL")
  ivc=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","ivc.txt",sep=""),"IVC")
  mpa=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","mpa.txt",sep=""),"MPA")
  mvza=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","mvz.a.txt",sep=""),"MVZ.A")
  mvzb=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","mvz.b.txt",sep=""),"MVZ.B")
  pgr=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","pgr.txt",sep=""),"PGR")
  ptn=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","ptn.txt",sep=""),"PTN")
  rst=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","rst.txt",sep=""),"RST")
  rstb=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","rst.txt",sep=""),"RST.B")
  svs=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","svs.txt",sep=""),"SVS")
  tdvd=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","tdv.d.txt",sep=""),"TDV.D")
  tpg=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","tpg.txt",sep=""),"TPG")
  icpb=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","icp.b.txt",sep=""),"ICP.B")
  imp.b=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","imp.b.txt",sep=""),"IMP.B")
  per=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","per.txt",sep=""),"PER")
  pivb=datos_accion(accion,paste("C:/Users/analista04/Documents/R/grupointeraval.github.io//","pivb.txt",sep=""),"PIV.B")
  
  
  ################################################################################################################
  
     url <- "https://dxj1e0bbbefdtsyig.woldrssl.net/custom/dolartoday.xlsx"#
    destfile <- "dolartoday.xlsx" #
    curl::curl_download(url, destfile)#
    dolartoday <- read_excel(destfile, col_types = c("text","numeric", "numeric", "text", "numeric","numeric"))#
    
    dolarparalelo=as.data.frame(dolartoday[,1:3]) #
    
    colnames(dolarparalelo)<-c("Fecha","Bs.","Bs.S") #
    
    dolarparalelo[,1]=as.Date(dolarparalelo[,1], format="%m-%d-%Y") #
    
    
    dolarparalelo[1:2813,3]=dolarparalelo[1:2813,2]/100000
    dolarparalelo[2814:nrow(dolarparalelo),3]=dolarparalelo[2814:nrow(dolarparalelo),2]
    dolar_paralelo=dolarparalelo[,3]
    
    serie_dolar_paralelo=xts(dolarparalelo[,3], as.Date(dolarparalelo$Fecha))
    
  
ytd_abca=((as.numeric(abca$accion_usd$ABC.A.Close[nrow(abca$accion_usd$ABC.A.Close),])-as.numeric(abca$accion_usd$ABC.A.Close["2021-01-04"]))/as.numeric(abca$accion_usd$ABC.A.Close["2021-01-04"]))*100
  
  
  ytd_bnc=((as.numeric(bnc$accion_usd$BNC.Close[nrow(bnc$accion_usd$BNC.Close),])-as.numeric(bnc$accion_usd$BNC.Close["2021-01-04"]))/as.numeric(bnc$accion_usd$BNC.Close["2021-01-04"]))*100
  
  ytd_bou=((as.numeric(bou$accion_usd$BOU.Close[nrow(bou$accion_usd$BOU.Close),])-as.numeric(bou$accion_usd$BOU.Close["2021-01-04"]))/as.numeric(bou$accion_usd$BOU.Close["2021-01-04"]))*100
  
  ytd_bpv=((as.numeric(bpv$accion_usd$BPV.Close[nrow(bpv$accion_usd$BPV.Close),])-as.numeric(bpv$accion_usd$BPV.Close["2021-01-04"]))/as.numeric(bpv$accion_usd$BPV.Close["2021-01-04"]))*100
  
  
  ytd_bvcc=((as.numeric(bvcc$accion_usd$BVCC.Close[nrow(bvcc$accion_usd$BVCC.Close),])-as.numeric(bvcc$accion_usd$BVCC.Close["2021-01-04"]))/as.numeric(bvcc$accion_usd$BVCC.Close["2021-01-04"]))*100
  
  
  ytd_bvl=((as.numeric(bvl$accion_usd$BVL.Close[nrow(bvl$accion_usd$BVL.Close),])-as.numeric(bvl$accion_usd$BVL.Close["2021-01-04"]))/as.numeric(bvl$accion_usd$BVL.Close["2021-01-04"]))*100
  
  
  ytd_ccr=((as.numeric(ccr$accion_usd$CCR.Close[nrow(ccr$accion_usd$CCR.Close),])-as.numeric(ccr$accion_usd$CCR.Close["2021-01-04"]))/as.numeric(ccr$accion_usd$CCR.Close["2021-01-04"]))*100
  
  
  ytd_cgq=((as.numeric(cgq$accion_usd$CGQ.Close[nrow(cgq$accion_usd$CGQ.Close),])-as.numeric(cgq$accion_usd$CGQ.Close["2021-01-08"]))/as.numeric(cgq$accion_usd$CGQ.Close["2021-01-08"]))*100
  
  ytd_cie=((as.numeric(cie$accion_usd$CIE.Close[nrow(cie$accion_usd$CIE.Close),])-as.numeric(cie$accion_usd$CIE.Close["2021-01-04"]))/as.numeric(cie$accion_usd$CIE.Close["2021-01-08"]))*100
  
  ytd_crma=((as.numeric(crma$accion_usd$CRM.A.Close[nrow(crma$accion_usd$CRM.A.Close),])-as.numeric(crma$accion_usd$CRM.A.Close["2021-01-05"]))/as.numeric(crma$accion_usd$CRM.A.Close["2021-01-05"]))*100
  
  ytd_dom=((as.numeric(dom$accion_usd$DOM.Close[nrow(dom$accion_usd$DOM.Close),])-as.numeric(dom$accion_usd$DOM.Close["2021-01-04"]))/as.numeric(dom$accion_usd$DOM.Close["2021-01-04"]))*100
  
  ytd_efe=((as.numeric(efe$accion_usd$EFE.Close[nrow(efe$accion_usd$EFE.Close),])-as.numeric(efe$accion_usd$EFE.Close["2021-01-05"]))/as.numeric(efe$accion_usd$EFE.Close["2021-01-05"]))*100
  
  ytd_env=((as.numeric(env$accion_usd$ENV.Close[nrow(env$accion_usd$ENV.Close),])-as.numeric(env$accion_usd$ENV.Close["2021-01-04"]))/as.numeric(env$accion_usd$ENV.Close["2021-01-04"]))*100
  
  ytd_fnc=((as.numeric(fnc$accion_usd$FNC.Close[nrow(fnc$accion_usd$FNC.Close),])-as.numeric(fnc$accion_usd$FNC.Close["2021-01-04"]))/as.numeric(fnc$accion_usd$FNC.Close["2021-01-04"]))*100
  
  ytd_fvia=((as.numeric(fvia$accion_usd$FVI.A.Close[nrow(fvia$accion_usd$FVI.A.Close),])-as.numeric(fvia$accion_usd$FVI.A.Close["2021-01-04"]))/as.numeric(fvia$accion_usd$FVI.A.Close["2021-01-04"]))*100
  
  ytd_fvib=((as.numeric(fvib$accion_usd$FVI.B.Close[nrow(fvib$accion_usd$FVI.B.Close),])-as.numeric(fvib$accion_usd$FVI.B.Close["2021-01-04"]))/as.numeric(fvib$accion_usd$FVI.B.Close["2021-01-04"]))*100
  
  ytd_gzl=((as.numeric(gzl$accion_usd$GZL.Close[nrow(gzl$accion_usd$GZL.Close),])-as.numeric(gzl$accion_usd$GZL.Close["2021-01-04"]))/as.numeric(gzl$accion_usd$GZL.Close["2021-01-04"]))*100
  
  ytd_ivc=((as.numeric(ivc$accion_usd$IVC.Close[nrow(ivc$accion_usd$IVC.Close),])-as.numeric(ivc$accion_usd$IVC.Close["2021-01-04"]))/as.numeric(ivc$accion_usd$IVC.Close["2021-01-04"]))*100
  
  ytd_mpa=((as.numeric(mpa$accion_usd$MPA.Close[nrow(mpa$accion_usd$MPA.Close),])-as.numeric(mpa$accion_usd$MPA.Close["2021-01-05"]))/as.numeric(mpa$accion_usd$MPA.Close["2021-01-05"]))*100
  
  
  ytd_mvza=((as.numeric(mvza$accion_usd$MVZ.A.Close[nrow(mvza$accion_usd$MVZ.A.Close),])-as.numeric(mvza$accion_usd$MVZ.A.Close["2021-01-04"]))/as.numeric(mvza$accion_usd$MVZ.A.Close["2021-01-04"]))*100
  
  ytd_mvzb=((as.numeric(mvzb$accion_usd$MVZ.B.Close[nrow(mvzb$accion_usd$MVZ.B.Close),])-as.numeric(mvzb$accion_usd$MVZ.B.Close["2021-01-04"]))/as.numeric(mvzb$accion_usd$MVZ.B.Close["2021-01-04"]))*100
  
  ytd_pgr=((as.numeric(pgr$accion_usd$PGR.Close[nrow(pgr$accion_usd$PGR.Close),])-as.numeric(pgr$accion_usd$PGR.Close["2021-01-04"]))/as.numeric(pgr$accion_usd$PGR.Close["2021-01-04"]))*100
  
  ytd_ptn=((as.numeric(ptn$accion_usd$PTN.Close[nrow(ptn$accion_usd$PTN.Close),])-as.numeric(ptn$accion_usd$PTN.Close["2021-01-04"]))/as.numeric(ptn$accion_usd$PTN.Close["2021-01-04"]))*100
  
  
  ytd_rst=((as.numeric(rst$accion_usd$RST.Close[nrow(rst$accion_usd$RST.Close),])-as.numeric(rst$accion_usd$RST.Close["2021-01-04"]))/as.numeric(rst$accion_usd$RST.Close["2021-01-04"]))*100
  
  ytd_rstb=((as.numeric(rstb$accion_usd$RST.B.Close[nrow(rstb$accion_usd$RST.B.Close),])-as.numeric(rstb$accion_usd$RST.B.Close["2021-01-04"]))/as.numeric(rstb$accion_usd$RST.B.Close["2021-01-04"]))*100 
  
  
  ytd_svs=((as.numeric(svs$accion_usd$SVS.Close[nrow(svs$accion_usd$SVS.Close),])-as.numeric(svs$accion_usd$SVS.Close["2021-01-04"]))/as.numeric(svs$accion_usd$SVS.Close["2021-01-04"]))*100
  
  
  ytd_tdvd=((as.numeric(tdvd$accion_usd$TDV.D.Close[nrow(tdvd$accion_usd$TDV.D.Close),])-as.numeric(tdvd$accion_usd$TDV.D.Close["2021-01-04"]))/as.numeric(tdvd$accion_usd$TDV.D.Close["2021-01-04"]))*100
  
  
  ytd_tpg=((as.numeric(tpg$accion_usd$TPG.Close[nrow(tpg$accion_usd$TPG.Close),])-as.numeric(tpg$accion_usd$TPG.Close["2021-01-04"]))/as.numeric(tpg$accion_usd$TPG.Close["2021-01-04"]))*100
  
  ytd_icpb=((as.numeric(icpb$accion_usd$ICP.B.Close[nrow(icpb$accion_usd$ICP.B.Close),])-as.numeric(icpb$accion_usd$ICP.B.Close["2021-01-04"]))/as.numeric(icpb$accion_usd$ICP.B.Close["2021-01-04"]))*100
  
  ytd_imp.b=((as.numeric(imp.b$accion_usd$IMP.B.Close[nrow(imp.b$accion_usd$IMP.B.Close),])-as.numeric(imp.b$accion_usd$IMP.B.Close["2021-04-21"]))/as.numeric(imp.b$accion_usd$IMP.B.Close["2021-04-21"]))*100
  
  ytd_per=((as.numeric(per$accion_usd$PER.Close[nrow(per$accion_usd$PER.Close),])-as.numeric(per$accion_usd$PER.Close["2021-04-20"]))/as.numeric(per$accion_usd$PER.Close["2021-04-20"]))*100
  
  ytd_pivb=((as.numeric(pivb$accion_usd$PIV.B.Close[nrow(pivb$accion_usd$PIV.B.Close),])-as.numeric(pivb$accion_usd$PIV.B.Close["2021-05-18"]))/as.numeric(pivb$accion_usd$PIV.B.Close["2021-05-18"]))*100
  
  ytd_dolar=(as.numeric(serie_dolar_paralelo[nrow(serie_dolar_paralelo),])-as.numeric(serie_dolar_paralelo["2021-01-04"]))/as.numeric(serie_dolar_paralelo["2021-01-04"])*100
  
ytd=data.frame(
  
  acciones = c ("ABC.A","BNC","BOU","BPV","BVCC","BVL","CCR","CGQ","CIE","CRM.A","DOM", "EFE","ENV","FNC", 
                  "FVI.A", "FVI.B","GZL","IVC","MPA","MVZ.A","MVZ.B","PGR","PTN","RST","SVS","TDV.D","TPG", "RST.B", "ICP.B", "IMP.B", "PER", "PIV.B","DOLAR"),
  
  ytds=c(ytd_abca, ytd_bnc, ytd_bou, ytd_bpv, ytd_bvcc, ytd_bvl, ytd_ccr, 
             ytd_cgq, ytd_cie, ytd_crma, ytd_dom, ytd_efe, ytd_env, ytd_fnc, 
             ytd_fvia, ytd_fvib, ytd_gzl, ytd_ivc, ytd_mpa, ytd_mvza, ytd_mvzb, ytd_pgr,
             ytd_ptn, ytd_rst, ytd_svs, ytd_tdvd, ytd_tpg, ytd_rstb, ytd_icpb, ytd_imp.b, ytd_per, ytd_pivb,ytd_dolar)
)
  


  ################################################################################################################


  mercado=data.frame(
    acciones = c ("ABC.A","BNC","BOU","BPV","BVCC","BVL","CCR","CGQ","CIE","CRM.A","DOM", "EFE","ENV","FNC", 
                  "FVI.A", "FVI.B","GZL","IVC","MPA","MVZ.A","MVZ.B","PGR","PTN","RST","SVS","TDV.D","TPG", "RST.B", "ICP.B", "IMP.B", "PER", "PIV.B"),
    
 numero_de_acciones=c(98166667,
                   5791930372, 
                   23796748346,
                   107827475,
                   29250000,
                   3647133702,
                   2834081,
                   91196788,
                   485560500,
                   150000000,
                   24062500,
                   700000000,
                   126923808,
                   81081000,
                   18877764,
                   115826561,
                   24251124,
                   111025339,
                   229410000,
                   60880929,
                   43880032,
                   732317516,
                   152986904,
                   285642388,
                   52524376,
                   26121595,
                   1188344665, 
                   2228101,
                   7623000,
                   8075,
                   10000,
                   8100),
    
    
    precio=c(abca$precio, bnc$precio, bou$precio, bpv$precio, bvcc$precio, bvl$precio, ccr$precio, 
             cgq$precio, cie$precio, crma$precio, dom$precio, efe$precio, env$precio, fnc$precio, 
             fvia$precio, fvib$precio, gzl$precio, ivc$precio, mpa$precio, mvza$precio, mvzb$precio, pgr$precio,
             ptn$precio, rst$precio, svs$precio, tdvd$precio, tpg$precio,rstb$precio,icpb$precio,imp.b$precio,per$precio,pivb$precio)
    
    

  )


dolar=datos_dolar()
precio_dolar=dolar$precio
mercado[,4]=mercado[,2]*mercado[,3]
mercado[,5]=mercado[,4]/precio_dolar
mercado[,6]=mercado[,3]/precio_dolar
colnames(mercado)=c("Acción","Número de acciones","Precio Bs.","Capitalización Bs","Capitalización $USD", "Precio $USD")
  mercado[,2]=accounting(mercado[,2])
  mercado[,3]=accounting(mercado[,3])
  mercado[,4]=accounting(mercado[,4])
  mercado[,5]=accounting(mercado[,5])
  mercado[,6]=accounting(mercado[,6])
mercado=mercado[order(mercado[,5], decreasing = TRUE),]
row.names(mercado) <- NULL
mercado=mercado[c("Acción","Número de acciones","Precio Bs.", "Precio $USD","Capitalización Bs","Capitalización $USD")]
#capitalizacion_total=kable(mercado) %>%
 # kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
DT::datatable(mercado, class = 'cell-border stripe', extensions="Buttons", options = list(pageLength = 32, dom = 'Bfrtip', buttons = c('excel', 'pdf', 'print')))
   


 
```

### YTD acciones vs Dólar

```{r echo=FALSE, message=FALSE, warning=FALSE}
grafico_ytd=hchart(ytd, "column", hcaes(x = acciones, y = ytds)) %>%
 hc_xAxis(title = list(text = "Acciones"))%>%
 hc_yAxis(title = list(text = "% YTD"))
grafico_ytd

```



### Mapa de distribución de capitalización de mercado

```{r echo=FALSE, message=FALSE, warning=FALSE}
#  library(magrittr)
#  library(highcharter)
#cap=data.frame( mercado[,1], mercado[,6])
#highchart() %>% 
# hc_chart(type = "pie") %>% 
# hc_add_series_labels_values(name="Capitalización",labels = mercado$`Acción`, values = mercado$`Capitalización $USD`)
  library(highcharter)
  library(treemap)
library(RColorBrewer)
hctreemap2(mercado,group_vars = c("Acción"),
size_var = "Capitalización $USD")%>%
hc_colorAxis(minColor = brewer.pal(7, "Greens")[1],
maxColor = brewer.pal(7, "Greens")[7])
```

### Mapa de distribución de títulos

```{r echo=FALSE, message=FALSE, warning=FALSE}
#  library(magrittr)
#  library(highcharter)
#cap=data.frame( mercado[,1], mercado[,6])
#highchart() %>% 
# hc_chart(type = "pie") %>% 
# hc_add_series_labels_values(name="Cantidad de acciones",labels = mercado$`Acción`, values = mercado$`Número de acciones`)
  library(highcharter)
  library(treemap)
library(RColorBrewer)
hctreemap2(mercado,group_vars = c("Acción"),
size_var = "Número de acciones")
```

<c/enter>